apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: backend
    name: backend
  ports:
    - port: 5000
      targetPort: 5000