apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: backend
    app: backend