FROM ubuntu:18.04
RUN apt-get update
ENV NODE_VERSION=14.15.0
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN apt-get install -y git
RUN npm install -g yarn
RUN mkdir /web
RUN git clone --depth=1 http://khuhub.khu.ac.kr/2021-1-capstone-design2/2015104215/ /web
RUN cd /web/project;yarn install
EXPOSE 3000
RUN cd /web/project;yarn build:web
WORKDIR /web/project
# CMD [ "yarn", "start:web" ]